# Generated by Django 3.2.7 on 2021-12-10 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('area_id', models.AutoField(primary_key=True, serialize=False)),
                ('area_name', models.CharField(max_length=150)),
                ('pincode', models.CharField(max_length=6)),
            ],
            options={
                'db_table': 'bloodbank_area',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('u_id', models.AutoField(primary_key=True, serialize=False)),
                ('u_name', models.CharField(max_length=50)),
                ('u_email', models.EmailField(max_length=254, unique=True)),
                ('u_contact', models.CharField(max_length=15)),
                ('u_pwd', models.CharField(max_length=15)),
                ('otp', models.CharField(max_length=10, null=True)),
                ('otp_used', models.IntegerField()),
                ('is_admin', models.IntegerField(default=0)),
                ('area_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bbank_admin.area')),
            ],
            options={
                'db_table': 'bloodbank_user',
            },
        ),
    ]
