# Generated by Django 3.2.7 on 2021-12-12 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bbank_admin', '0002_auto_20211211_2020'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blood_grp',
            old_name='bloodgrp_tyep',
            new_name='bloodgrp_type',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='id',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='id',
        ),
        migrations.RemoveField(
            model_name='request_blood',
            name='id',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='appointment_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='gallery_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='request_blood',
            name='request_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('f_id', models.AutoField(primary_key=True, serialize=False)),
                ('feedback_b', models.CharField(max_length=200)),
                ('f_date', models.DateTimeField()),
                ('b_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bbank_admin.bloodbank')),
                ('d_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bbank_admin.donor')),
                ('receiver_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bbank_admin.receiver')),
            ],
            options={
                'db_table': 'bloodbank_feedback',
            },
        ),
    ]
