# Generated by Django 3.2.7 on 2021-12-14 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bbank_admin', '0003_auto_20211212_1453'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receiver',
            old_name='donor_weight',
            new_name='receiver_weight',
        ),
    ]
